### ISSUE TITLE
Wallpaper for NixOS

### ISSUE THREAD

**Issue by figsoda** [dracula/wallpaper#10]
It would be great if there is a [NixOS](https://nixos.org) spin of this wallpaper.

**Comment by shadowrylander** [comment]
Was just thinking about this!

**Comment by brandon-irs** [comment]
Write down, sorry for the delay.

**Comment by Jasmine-Thorqua** [comment]
[https://github.com/Jasmine-Thorqua/dracula_wallpaper_nixos](url)
