### ISSUE TITLE
wallpaper for xubuntu

### ISSUE THREAD

**Issue by philipzae** [dracula/wallpaper#2]
Please create one for xubuntu. Logo can be found here https://static.xubuntu.org/xubuntu_brand/Logo/

**Comment by aostephano** [comment]
Take a look [https://github.com/dracula/wallpaper/blob/c066ff599a95afca39b0516c235bcad5ccc14959/xubuntu.png](url)

**Comment by aostephano** [comment]
Take a look :)
[https://github.com/dracula/wallpaper/blob/c066ff599a95afca39b0516c235bcad5ccc14959/xubuntu.png](url)

**Comment by aostephano** [comment]
Take a look :)
https://github.com/dracula/wallpaper/blob/c066ff599a95afca39b0516c235bcad5ccc14959/xubuntu.png

**Comment by philipzae** [comment]
looks great. thanks.

**Comment by zenorocha** [comment]
Merged, thanks @aostephano!
