### ISSUE TITLE
Request: vertical base wallpaper

### ISSUE THREAD

**Issue by snessim** [dracula/wallpaper#23]
I was able to make a vertical version of the base wallpaper by pasting it over an Android wallpaper and fiddling with layer scale and position, but it would be nice to have a pre-made version for those who can't do that. Pretty much just a 9:16 version of the Android wallpaper, but with the Android logo removed.
![baseFHD9_16](https://user-images.githubusercontent.com/20545957/125177493-13956f00-e191-11eb-868a-666e6891e902.png)

**Comment by brandon-irs** [comment]
Done: f761e88
