### ISSUE TITLE
Request: Add Zorin OS wallpaper (I made one)

### ISSUE THREAD

**Issue by NoEnd-yt** [dracula/wallpaper#26]
I made a Zorin OS dracula wallpaper with [base.png](https://github.com/dracula/wallpaper/blob/master/base.png) and the Zorin OS logo with the right colors on Gimp. Can someone add it to the main wallpaper repo?
Here it is:
![zorin](https://user-images.githubusercontent.com/76617157/132538160-389d385e-31c7-4782-aba4-2a09e3ee3133.png)

**Comment by brandon-irs** [comment]
Done: f761e88
